apiVersion: v1
kind: Service
metadata:
  name: dotnet-refresh-api-service
spec:
  selector:
    app: dotnet-refresh-api-pod
  ports:
  - name: http
    port: 8080
    targetPort: 80
  type: LoadBalancer
