apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-refresh-db-deployment
spec:
  selector:
    matchLabels:
      app: dotnet-refresh-db-pod
  template:
    metadata:
      labels:
        app: dotnet-refresh-db-pod
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mssql
        image: mcr.microsoft.com/mssql/server:2017-latest
        ports:
        - containerPort: 1433
        env:
        - name: MSSQL_PID
          value: "Developer"
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mssql-secrets
              key: SA_PASSWORD
        volumeMounts:
          - name: mssql-data
            mountPath: /var/opt/mssql
      volumes:
        - name: mssql-data
          persistentVolumeClaim:
            claimName: mssql-data-disk
