apiVersion: v1
kind: Service
metadata:
  name: dotnet-refresh-db-service
spec:
  selector:
    app: dotnet-refresh-db-pod
  ports:
  - protocol: TCP
    port: 1433
    targetPort: 1433
  type: LoadBalancer
